### ISSUE TITLE
provide a cdn version build by umd

### ISSUE THREAD

**Issue by rowthan** [bitovi/react-to-web-component#111]
how about provide a umd link for this lib?

**Comment by christopherjbaker** [comment]
Do you have a use case for this? We used to publish one that could work in a `<script>` tag, but React doesn't work well in a browser this way, so we didn't have a use-case for R2WC to do that.

**Comment by rowthan** [comment]
I have build several web component. and will be used in a page.  I think it would be better with a UMD lib shared with them.
maybe faster?

**Comment by justinbmeyer** [comment]
I doubt it will be much faster.  However, react's docs show using react locally as the first example:

![image](https://github.com/bitovi/react-to-web-component/assets/78602/25798c15-a2b1-40f4-80da-6fd71eb0abea)

this loads from script tags from a unpkg: https://gist.githubusercontent.com/gaearon/0275b1e1518599bbeafcde4722e79ed1/raw/db72dcbf3384ee1708c4a07d3be79860db04bff0/example.html

It's always worth making it easy to use R2WC.  Seems like even more of a priority given the context this tool is used in (folks wanting to add a few quick script tags and have things work)
