### ISSUE TITLE
Fixing moving the wc dom elements around, and multiple times setting a "function" prop

### ISSUE THREAD

**Issue by meboev-fourth** [bitovi/react-to-web-component#113]
You should take a look at this patch I made, and consider releasing it. It fixes 2 major issues.
version 2.0.2, core version 1.0.0
[@r2wc+core+1.0.0.patch](https://github.com/bitovi/react-to-web-component/files/11638706/%40r2wc%2Bcore%2B1.0.0.patch)

**Comment by meboev-fourth** [comment]
Here are some use cases in a CRA app, for setting props/attributes of a web component. Pay attention of the second case, it should have not been possible without the `type === "function" ? ...` part of the patch

> <outlined-dropdown id="outlined-dropdown1"></outlined-dropdown>

      <script>
        const el1 = document.getElementById('outlined-dropdown1');
        const options1 = [{ label: "no value", value: "" }, { label: "label 1", value: "1" }, { label: "label 2", value: "2" }];
        const optionsJson1 = JSON.stringify(options1);
        el1.setAttribute('label', 'dropdown label 1');
        el1.setAttribute('placeholder', 'placeholder 1');
        el1.setAttribute('value', '1');
        el1.setAttribute('required', 'true');
        el1.setAttribute('options', optionsJson1);
        el1.setAttribute('on-change', '__myOnChange__');
        window.__myOnChange__ = (e) => {
          console.log('Selected 1', {
            value: e.target.value,
            label: options1.find((o) => o.value === e.target.value)?.label
          });
        };
      </script>
      <outlined-dropdown
        id="outlined-dropdown2"
        label="dropdown label 2"
        options='[{ "label": "no value", "value": "" }, { "label": "label 1", "value": "1" }, { "label": "label 2", "value": "2" }]'
        placeholder="placeholder 2"
        error-text="error text 2"
        required="true"
        test-id="outlined-dropdown-test-id-2"
      ></outlined-dropdown>
      <script>
        document.addEventListener('DOMContentLoaded', () => { // because of the CRA bundle.js script is deferred
          const el2 = document.getElementById('outlined-dropdown2');
          window.__myOnChange2__ = (e) => {
            console.log('Selected 2', { value: e.target.value });
          };
          el2.onChange = '__myOnChange2__'; // window.__myOnChange2__ should already be there
          delete window.__myOnChange2__; // we can even delete this from window now
        });
      </script>

**Comment by ahessami** [comment]
This is a nice solution, thanks for posting it!  I was experiencing the issue with the React error: "Cannot update an unmounted root."

**Comment by meboev-fourth** [comment]
Here's a new addition to the patch: Ability to hook directly a "function" prop, without "window". It turns off attribute updating the DOM, on component prop setting / which is a feature by itself :) /

[@r2wc+core+1.0.0.patch](https://github.com/bitovi/react-to-web-component/files/12549548/%40r2wc%2Bcore%2B1.0.0.patch)

Usage:

```
      <outlined-dropdown id="outlined-dropdown1"></outlined-dropdown>
      <script>
        (() => {
          const component = document.getElementById('outlined-dropdown1');
          const options = [{ label: "no value", value: "" }, { label: "label 1", value: "1" }, { label: "label 2", value: "2" }];
          const optionsJson = JSON.stringify(options);
          component.setAttribute('label', 'dropdown label 1');
          component.setAttribute('placeholder', 'placeholder 1');
          component.setAttribute('value', '1');
          component.setAttribute('required', 'true');
          component.setAttribute('options', optionsJson);
          component.setAttribute('on-change', '__myOnChange__');
          window.__myOnChange__ = (e) => {
            console.log('Selected 1', {
              value: e.target.value,
              label: options.find((o) => o.value === e.target.value)?.label
            });
          };
        })();
      </script>
      <outlined-dropdown
        id="outlined-dropdown2"
        test-id="outlined-dropdown-test-id-2"
      ></outlined-dropdown>
      <script>
        document.addEventListener('DOMContentLoaded', () => { // because of the CRA bundle.js script is deferred
          const component = document.getElementById('outlined-dropdown2');
          const options = [{ label: "no value", value: "" }, { label: "label 3", value: "3" }, { label: "label 4", value: "4" }];
          const optionsJson = JSON.stringify(options);
          component.options = options;
          component.label = "dropdown label 2";
          component.placeholder = "placeholder 2";
          component.errorText = "error text 2";
          component.required = true;
          component.onChange = (e) => {
            console.log('Selected 2', { value: e.target.value });
          };
        });
      </script>
```
