### ISSUE TITLE
Moving from 2.0.0-alpha.0 to 2.0.0 causes 2nd property of a component to be undefined

### ISSUE THREAD

**Issue by jscott-resilient** [bitovi/react-to-web-component#119]
Hello! Just spotted this error and was wondering if you had any suggestions to fix this? (Or if its a bug)

Using the component like so:

`<collaborate-sidebar-section customer-id={'customerId'} call-id={'callId'} />`

would lead to this error "Warning: Failed prop type: The prop `call-id` is marked as required in `StyledCollaborateSidebarSectionWrapper`, but its value is `undefined`"

When swapping the order of the properties in the component like this:

`<collaborate-sidebar-section call-id={'callId'} customer-id={'customerId'} />`

`customer-id` would then be undefined.

For now I've reverted back to `2.0.0-alpha.0`. This error occurred in chrome v114.0.5735.106 with a react web component create from react v17.0.2. If you need anything else please let me know!

Joe

**Comment by jscott-resilient** [comment]
I've just done a little testing and it seems to be `2.0.0-alpha.5` where I encounter the issue, `2.0.0-alpha.4` works as expected!

**Comment by christopherjbaker** [comment]
That is not expected behaviour, and I'm not sure what would be causing it. Do you also experience this with `@r2wc/react-to-web-component@2`?

**Comment by rohitdutta1000** [comment]
@christopherjbaker I'm still having this issue personally and I'm using v2

**Comment by jscott-resilient** [comment]
Hello! Sorry for the late response! As we are using react 17 `@r2wc/react-to-web-component` v2 does not work with our app, but when I tried v1.0.0 I get the same issue. The changes I see between 2.0.0-alpha.4 -> 2.0.0-alpha.5 are here https://github.com/bitovi/react-to-web-component/commit/4b323ce04813773fdaf387ae3924b5b589f701dc

is `transform?.parse` not being defined?

We are planning on moving to react 18 so could see if this issue persists afterwards (this will be a little while away though)

**Comment by christopherjbaker** [comment]
Would you be able to put together a minimal use case of this? I'm not sure what would cause it and am unable to reproduce.

**Comment by jscott-resilient** [comment]
We have moved over to react 18 and it works as expected! So it looks like react 17 was the problem
