### ISSUE TITLE
MUI Shadow DOM support

### ISSUE THREAD

**Issue by stevenalanstark** [bitovi/react-to-web-component#120]
I am trying to show how to use MUI with the shadow DOM, but am failing to see how it works.

I require the shadow DOM in order to support WC children in the WC, see: https://github.com/bitovi/react-to-web-component/issues/114

After using slots, I am now able to have a WC be a child of another WC, however the shadow DOM breaks the MUI Theme

MUI has an interesting article here:
https://mui.com/material-ui/guides/shadow-dom/

The problem is that I cannot create a cache of the DOM because I can't seem to reference the root node from the WC in order to create the cache. 

Is there a way to support MUI in the shadow DOM?

**Comment by christopherjbaker** [comment]
We have a solution, though we've not fully documented it yet (and there will be a companion library to simplify it soon).

The primary component passed into `r2wc` gets one extra prop passed in: `container`. This is the root element (or shadow element if applicable). You can tell Emotion to insert its styles there instead of the head:
```
const cache = useMemo(() => createCache({ container }), [container])

return (
  <CacheProvider value={cache}>
    <App />
  </CacheProvider>
)
```

**Comment by alejandra-moreno-espinar** [comment]
Hi!
I am trying to setup this solution. Would you mind sharing the html code where you set the container prop of the web component? I am somehow lost as createCache is expecting a Node for container. Thanks!

**Comment by christopherjbaker** [comment]
@alejandra-moreno-espinar The latest version (anything in the `@r2wc` namespace) passes an additional prop called `container` that will be the actual DOM element node to use as you need. The emotion wrapper will literally just take that value and pass it into the cache in the above code.
