### ISSUE TITLE
pass in data ( JSON ) as a property, useful for SSR

### ISSUE THREAD

**Issue by stevenalanstark** [bitovi/react-to-web-component#121]
Like with the similar project "remount" ( https://github.com/rstacruz/remount ), does this project support passing in JSON data for server side rendered applications that are able to pass data in as a property?

`JSON props (eg, <x-greeter props-json="{...}">)`

**Comment by SeedyROM** [comment]
Yup! You can set the type of a `r2wc` property to `"json`".

https://github.com/bitovi/react-to-web-component#working-with-attributes
