### ISSUE TITLE
What about web components?

### ISSUE THREAD

**Issue by Lory1990** [bitovi/react-to-web-component#130]
Hi everyone!
I tried Web Components and Styled Components together and they work well... the only thing is that the theme is not shared across the host and the child. 

Now I am sharing the theme as an attribute but it is not the best solution

```
import theme from '../../../'

[...]

<rwc-app theme={JSON.stringify(theme)}/> 
```

**Comment by christopherjbaker** [comment]
React Context does not pass between nested React instances, so there's no way to directly share it between web components either. What I've done here is to put the theme on the window, then each WC can grab it from the window to use inside the WC like you're likely using your `theme` value here.

I have some ideas of a context equivalent for web components, but that's a side idea at best right now.
