### ISSUE TITLE
Function prop generates function is not defined error

### ISSUE THREAD

**Issue by Elyes3** [bitovi/react-to-web-component#133]
I created a function using Angular and I'm trying to pass it into r2wc React web component. It doesn't get passed and I'm getting an error ( g is not a function )

**Comment by mario-serna** [comment]
I was facing this issue, but as a workaround I made a change in the transform function to dispatch an Event with the prop name. So in my angular app I just added a event listener to trigger my method.

> @r2wc/core/transforms/function.ts
```ts
import type { Transform } from "./index"

const string: Transform<(...args: unknown[]) => unknown> = {
  stringify: (value) => value.name,
  parse: (value, element) => {
    const dispatch = (): any => {
      element.dispatchEvent(new Event(value, {}))
    }

    const fn = (() => {
      return dispatch
    })()

    return fn.bind(element)
  },
}

export default string
```

> Angular app html
```html
<react-doc-viewer [file]="file" action="action"> </react-doc-viewer>
```
> Angular app component
```ts
ngAfterViewInit(): void {
    const doc = document.getElementsByTagName('react-doc-viewer')[0];
    doc.addEventListener('action', () => this.action());
  }

  action() {
    console.log(`Current file ${this?.file}`);
    alert(`Current file ${this?.file}`);
  }
```

**Comment by christopherjbaker** [comment]
It looks like this is solved, so I'm going to close this. We are looking into better supporting usage within Angular though!
