### ISSUE TITLE
How can one build a Web Component and then import it into the website?

### ISSUE THREAD

**Issue by Vulwsztyn** [bitovi/react-to-web-component#134]
Hi,
your library seems to exactly match my use-case (creating web components with mui or elastic ui to be used in angular), but I do not understand how I am supposed to use it to build the js file/bundle and then import it into the html of the website.
I found https://github.com/bmomberger-bitovi/web-components-example, but still failed to get the components to work.

**Comment by daniel-ricado** [comment]
gotta admit the docs seem to completely omit how do build and import the web component.

**Comment by Vulwsztyn** [comment]
Yeah, but even after they are built I have a problem with importing them: https://github.com/bmomberger-bitovi/web-components-example/issues/1

**Comment by tcoopman** [comment]
I think I have the same issue, I can build the umd files, but when I import that file in a <script> tag in html and then try to use the webcomponents, nothing happens (no errors, and the file is loaded).
It would be great if you could give an example on how to use the webcomponents in html directly.

**Comment by Vulwsztyn** [comment]
@tcoopman I went with this https://github.com/Vulwsztyn/preact-web-component/tree/main

**Comment by tcoopman** [comment]
I've got it working. I messed up the dependencies files, and overwrote some of my own stuff by accident.

**Comment by christopherjbaker** [comment]
I apologize; my github email notifications were not set up right. It looks like you solved it the way I would have.

For anybody else who stumbles upon this, our [main example](https://codesandbox.io/s/sample-greeting-app-ts-qwidh9?file=/public/index.html) should have what you're looking for. The Vite output js file can be added to any HTML page, then all you need to do is add the appropriate `<web-app />` tag to the page as needed.

**Comment by tombohub** [comment]
@christopherjbaker why are you saying vite? I don't see vite in that example. I've copied this example but I get this error:
```
> react-scripts build

Could not find a required file.
  Name: index.js
  Searched in: D:\PROJECTS\react-ui-libraries\example-components\mui\button\src
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tombohub** [comment]
@tcoopman can you please share an example how you did it?

**Comment by tombohub** [comment]
@daniel-ricado how do we run this build:wc command?

**Comment by Vulwsztyn** [comment]
look at package.json

**Comment by tombohub** [comment]
@Vulwsztyn thanks, Ive managed to do it, but web component size for MUI button is 200kb. Is the same for you? I have tried with preact and component size is 50kb. Is there any way to make it smaller?

**Comment by Vulwsztyn** [comment]
You will be better of creating the component with preact. check it out
