### ISSUE TITLE
Issue with passing function prop to web component

### ISSUE THREAD

**Issue by gs-vkinti** [bitovi/react-to-web-component#158]
We have React component (`Counter`) and converted into web-component with `r2wc` and publishing as `NPM` package.

Using `"@r2wc/react-to-web-component": "^2.0.3"`

```
import "./counter.scss";

import { memo, useState } from "react";

const Counter = (props: any) => {
  console.log("counter props", props);

  const [count, setCount] = useState(0);

  return (
    <div>
      <div className="counter">
        <div className="counter__count">{count}</div>
        <div className="counter__buttons">
          <button onClick={() => setCount(count + 1)}>Increment</button>
          <button onClick={() => setCount(count - 1)}>Decrement</button>
        </div>

        <div
          onClick={() =>  props.onAction() }
          className="counter__click-me"
        >
          Click Me
        </div>

        <div className="counter__my-object">
          <pre>{JSON.stringify(props.myObject, null, 2)}</pre>
        </div>
      </div>
    </div>
  );
};

export default memo(Counter);
```

Convert the `Counter` React component into `my-counter` web-component

```
import r2wc from "@r2wc/react-to-web-component";

import { Counter } from "./";

window.customElements.get("my-counter") ||
  window.customElements.define(
    "my-counter",
    r2wc(Counter, {
      props: {
        name: "string",
        onAction: "function",
        myObject: "json",
      },
      shadow: "open",
    })
  );

```

We are consuming the web component in another React project. 

```
<my-counter
      name={this.state.name}
      on-action={() => alert("on action called")}
      my-object={JSON.stringify({ name: this.state.name })}
/>
```

we have console log for printing the `props` in `Counter` component which not showing the `onAction` prop

```
{
   container: document-fragment
   myObject: {name: 'test'}
   name: "test"
}
```

We are thinking this is because of https://github.com/bitovi/react-to-web-component/blob/002a007c40fa67fc95c9cddbfde335b22a949ed8/packages/core/src/transforms/function.ts#L7  it checks the function exists in  `Window` or `global` objects. 

Then we are changed way of passing function to web-component as like then it's working

```
UNSAFE_componentWillMount() {
    window.onAction = () => {
      this.setState({ name: Date.now() })
    }
}

componentWillUnmount() {
   delete window.onAction;
}
<my-counter
      name={this.state.name}
      on-action="onAction"
      my-object={JSON.stringify({ name: this.state.name })}
/>
```

Can't we pass direct JS function to web components?

cc: @christopherjbaker

**Comment by Chrisdo82** [comment]
In principle, this could be done with Custom Elements, but the approach chosen here is to represent everything in attributes. 

In my opinion, it would be better if we were able to set complex data structures as properties, and not try to parse everything as a string or set it on the Window object.

**Comment by christopherjbaker** [comment]
Web Components are added in the DOM, which only supports strings as values. We make that a little bit better by adding parsing for things like numbers/booleans/json, but there's no way to cleanly and safely pass a stringified function. It's not a great solution, but that's why we added the global function option.

There _is_ another way though, exactly what @Chrisdo82 suggested: You can get the dom element and set those values directly.

```javascript
// <my-counter id="counter" name={this.state.name} />

const counter = document.getElementById("counter")
counter.onAction = () => alert("on action called")
counter.myObject = { name: this.state.name }
```

**Comment by gs-vkinti** [comment]
@christopherjbaker Thank you for your suggestion. 

How we can listen the `myObject` change in web component (React component)?

**Comment by zeeshanshaheenn3o** [comment]
// <my-counter id="counter" name={this.state.name} />

const counter = document.getElementById("counter")
counter.onAction = () => alert("on action called")
counter.myObject = { name: this.state.name }

@Chrisdo82 then we can't use props.onAction or props.myObject.
we have to user props.container.onAction inside react component ?..


is their i way that i simply call props.onAction like we usually do inside react.
