### ISSUE TITLE
React 19

### ISSUE THREAD

**Issue by holgergp** [bitovi/react-to-web-component#211]
Now that React 19 is here: 
This package does sadly not work with React 19, due to an explicit peer dependency: https://github.com/bitovi/react-to-web-component/blob/main/packages/core/package.json
Any plans to upgrade that, or do you know of any roadblocks that prevent this?

If you like I could provide the PR for this.

Thanks for the great work!!

**Comment by bmomberger-bitovi** [comment]
Hi Holger,

Would you mind grabbing a copy of the source and trying it out with React 19 added as a peer dependency?  If the test suite passes, your own smoke tests also work, and there isn't an API change, I can update package.json and release next week.  Thanks!

**Comment by holgergp** [comment]
Hi Brad,

thanks for your answer! I added the peer dependencies here: https://github.com/bitovi/react-to-web-component/pull/212
The project builds properly, the test suite pass in each subproject (`npm run test` run in each subproject). 
I force updated the `devDependency` in `react-to-webcomponents` to 19, such that the tests run with react 19 API. That also passes.
The only thing I could not manage to do was to check out the actual build library. 
How do you link a dev version of this lib to a consuming app?

**Comment by bmomberger-bitovi** [comment]
From your consuming application, enter `npm link <path>` with `<path>` replaced with root of the react-to-web-component package. This will replace your existing installed version with a symlink to the lib folder.  As long as you have run the `build` npm script from within react-to-web-component, it should then be seamlessly usable in your app.

**Comment by holgergp** [comment]
Ah! Thanks! That worked! Looking good on my side.

**Comment by bmomberger-bitovi** [comment]
React 19 support now in the latest releases of @r2wc/react-to-web-component (2.0.4) and legacy react-to-webcomponent (2.0.1).  Closing.
