### ISSUE TITLE
Props are not available in production build but available in development

### ISSUE THREAD

**Issue by bahag-xvisnei** [bitovi/react-to-web-component#52]
Hi, 

I created a typescript-based react app using create-react-app and added a simple react component, which I converted to a web component. If run this in development mode, the props are populated with values. However, If I build it for production and run it, the props' values are not set. Is this about how it is build? Do I need to set some flags or enable features on production build?
```
interface ColorMixerProps {
  productNumber: string;
  preview: string;
}

class ColorMixerApp extends React.Component<ColorMixerProps, any> {
  render() {
    console.log("props:", this.props);
    return (
        <p>Hello React-To-Webcomponent</p>
    );
  }
}

// @ts-ignore
ColorMixerApp.propTypes = {
  productNumber: PropTypes.string.isRequired,
  preview: PropTypes.string.isRequired,
};

// @ts-ignore
customElements.define("color-mixer", reactToWebComponent(
    ColorMixerApp,
    React,
    ReactDOM,
    { dashStyleAttributes: true }
));
```
Inside index.html:
`<color-mixer  id="color-mixer-preview"  product-number="987654321"  preview="true"></color-mixer>`

Thanks

**Comment by bahag-xvisnei** [comment]
Hi,

During googling the issue, I found babel-plugin-transform-react-remove-prop-types package, which, I suppose, removes the propTypes. Unfortunately, in package-lock.json there is a reference to it. that could be the root cause but I am not sure.

**Comment by bahag-xvisnei** [comment]
Hi again,

After struggling with this, I am sure now that it was babel-plugin-transform-react-remove-prop-types, who removed the propTypes from the react component.

I also noticed that propTypes won't be required anymore after merging the R2WC-19-pass-handlers branch. I tested it locally and it works for my usecase. 

I hope that you release it really soon.

Thanks, Ilhami

**Comment by justinbmeyer** [comment]
Would something like the following work:

```
const propType = "prop"+"Type";
Object.defineProperty(ColorMixerApp,propType, {
  value: {
    productNumber: PropTypes.string.isRequired,
    preview: PropTypes.string.isRequired,
  }
})
```

Or, is it that `PropTypes` itself is removed in prod?

**Comment by roicahana** [comment]
I'm having the same issue. If the issue is with Babel, do you know of a workaround instead of ejecting React and changing the Babel/Webpack configuration?

**Comment by zerico007** [comment]
this issue is solved in the new [v2](https://www.npmjs.com/package/@r2wc/react-to-web-component)
