### ISSUE TITLE
How to send children prop in the custom HTML element created

### ISSUE THREAD

**Issue by Abhishek-Rajendra** [bitovi/react-to-web-component#7]
Let say I want something inside the `<text-x> Hi </text-x>`, I tried using `<text-x children="Hi"></text-x>` both didn't work

**Comment by justinbmeyer** [comment]
Can you share what your component looked like?

**Comment by linuxonrails** [comment]
Same problem.

Example component:

js/tsx:
```tsx
import * as React from 'react';
import * as PropTypes from 'prop-types';

export const Foobar = (props) => {
  console.log({ props });
  return (
    <div>
      headingtitle prop: { props.headingtitle }
      <br />
      children prop:<br />
      { props.children }
    </div>
  );
}

Foobar.propTypes = {
  headingtitle: PropTypes.string,
  children: PropTypes.node,
};

export default Foobar;
```

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import reactToWebComponent from 'react-to-webcomponent';

import { Foobar } from 'common/components/Foobar';

const FoobarAsWebComponent = reactToWebComponent(Foobar, React, ReactDOM);
customElements.define('foo-bar', FoobarAsWebComponent);
```

HTML:
```html
        <foo-bar headingtitle="Heading title prop">
          <p>Todo lo que ves en nuestro catálogo. Tenemos a la venta más de 24.000.000 de lotes de más de 20.000 vendedores distintos.</p>
        </foo-bar>
```

console.log: `props: { headingtitle: "Heading title prop" }`

![Screenshot (18)](https://user-images.githubusercontent.com/248779/105329251-3b881a80-5bd1-11eb-87f7-5238c463c3da.png)

**Comment by StormRaider2495** [comment]
I am having a similar issue. But its happening post build with the attribute passed to the custom element.
After build the value is not getting passed to the react component from index.html

**Comment by justinbmeyer** [comment]
Thanks @linuxonrails for trying to summarize this for me.  I'm not actually much of a react dev (much more of a webcomponent dev).  

Just to confirm the expected behavior ... it seems like `props.children` is react's version of a shadow/light DOM concept.

Is `props.children` always static? Its fully rendered contents are always passed down to the child component?

**Comment by leanderseige** [comment]
Not sure if I understand the problem but I can set props like this:

```
window.addEventListener('DOMContentLoaded', (event) => {
  var root = document.getElementById("id")
  var mywc = document.createElement('mywc')
  mywc.settings = "settings"
  root.appendChild(mywc)
}
```

**Comment by PtAuDev** [comment]
How is it going by now ?

**Comment by christopherjbaker** [comment]
This is something we are looking into, but I don't have any progress updates at the moment. It is requiring some exploration because React expects children to be jsx or other renderable content that it can turn into DOM nodes; there's no way to give it content that is _already_ DOM nodes.

**Comment by bertrand-riviere** [comment]
Unless there is something I don't understand, having "DOM children" can be done as described in this article (using a "slot"):
https://gilfink.medium.com/wrapping-react-components-inside-custom-elements-97431d1155bd

**Comment by christopherjbaker** [comment]
@bertrand-riviere That does look promising! It will still require some exploration to integrate it in a generic way, but we'll be picking this up soon.
