### ISSUE TITLE
Running an error in the Angular environment

### ISSUE THREAD

**Issue by fromIceWorld** [bitovi/react-to-web-component#97]
**error:**
`Uncaught TypeError: Cannot use 'in' operator to search for 'adoptedCallback' in undefined`

**code area:**
` 
 getOwnPropertyDescriptor: function (target, key) {
      var own = Reflect.getOwnPropertyDescriptor(target, key)
      if (own) {
        return own
      }
      if (key in ReactComponent.propTypes) {
        return {
          configurable: true,
          enumerable: true,
          writable: true,
          value: undefined,
        }
      }
    },
`

**failure reason:** 
In the Angular runtime environment, ReactComponent.propTypes will be empty

**resolvent:**
` 
 getOwnPropertyDescriptor: function (target, key) {
      var own = Reflect.getOwnPropertyDescriptor(target, key)
      if (own) {
        return own
      }
      if (ReactComponent.propTypes && key in ReactComponent.propTypes) {
        return {
          configurable: true,
          enumerable: true,
          writable: true,
          value: undefined,
        }
      }
    },
`
**notes:**
Similar issues also exist in other places

**Comment by zerico007** [comment]
Hey. we removed dependence on proptypes in v2. Download the new `[r2wc](https://www.npmjs.com/package/@r2wc/react-to-web-component)`
